In [40]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.20.0'

In [41]:
( x_train, y_train_old ), ( x_test, y_test_old ) = tf.keras.datasets.mnist.load_data()

print ( x_train.shape )
print ( x_test.shape )
print ( y_train_old.shape )
print ( y_test_old.shape )

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


### Flatten each individual image so that we can feed it as a 1D vector into the neural network

In [42]:
x_train = x_train.reshape ( -1, 28 * 28 )
x_test = x_test.reshape ( -1, 28 * 28 )
print ( x_train.shape )
print ( x_test.shape )

(60000, 784)
(10000, 784)


### Each y label is an integer, so convert to one hot labels. We are doing this because softmax is used, which will output a list of probabilities

In [43]:
y_train = tf.one_hot ( tf.cast ( y_train_old, dtype = tf.int32 ), depth = 10 )
y_test = tf.one_hot ( tf.cast ( y_test_old, dtype = tf.int32 ), depth = 10 )
print ( y_train.shape )
print ( y_test.shape )

(60000, 10)
(10000, 10)


### gelu is a better relu :)

In [54]:
model = tf.keras.Sequential ( [
    tf.keras.layers.InputLayer ( input_shape = ( 784, ) ),
    tf.keras.layers.Dense ( 256, activation = 'gelu' ),
    tf.keras.layers.Dense ( 128, activation = 'gelu' ),
    tf.keras.layers.Dense ( 10, activation = 'softmax' )
] )

In [55]:
opt = tf.keras.optimizers.Adam ( learning_rate = 0.001 )
model.compile ( optimizer = opt, loss = "categorical_crossentropy" )

In [56]:
model.fit ( x_train, y_train, epochs = 14, batch_size = 64, verbose = 2, validation_split = 0.2 )

Epoch 1/14
750/750 - 4s - 5ms/step - loss: 2.4104 - val_loss: 0.5301
Epoch 2/14
750/750 - 3s - 4ms/step - loss: 0.3010 - val_loss: 0.2866
Epoch 3/14
750/750 - 3s - 4ms/step - loss: 0.1886 - val_loss: 0.2590
Epoch 4/14
750/750 - 3s - 4ms/step - loss: 0.1488 - val_loss: 0.2210
Epoch 5/14
750/750 - 3s - 4ms/step - loss: 0.1407 - val_loss: 0.2371
Epoch 6/14
750/750 - 3s - 4ms/step - loss: 0.1207 - val_loss: 0.1933
Epoch 7/14
750/750 - 3s - 4ms/step - loss: 0.1043 - val_loss: 0.1928
Epoch 8/14
750/750 - 3s - 4ms/step - loss: 0.1062 - val_loss: 0.1718
Epoch 9/14
750/750 - 3s - 4ms/step - loss: 0.0959 - val_loss: 0.1651
Epoch 10/14
750/750 - 3s - 4ms/step - loss: 0.0889 - val_loss: 0.1594
Epoch 11/14
750/750 - 3s - 4ms/step - loss: 0.0830 - val_loss: 0.1559
Epoch 12/14
750/750 - 3s - 4ms/step - loss: 0.0755 - val_loss: 0.1858
Epoch 13/14
750/750 - 3s - 4ms/step - loss: 0.0686 - val_loss: 0.1642
Epoch 14/14
750/750 - 3s - 4ms/step - loss: 0.0732 - val_loss: 0.1791


### Final report!

In [65]:
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_probs = model.predict ( x_test )
y_pred = np.argmax ( y_probs, axis = 1 )
y_true = np.argmax ( y_test, axis = 1 )

acc = accuracy_score ( y_true, y_pred )
print ( "Test accuracy:", acc )

print ( "Confusion matrix: " )
print ( confusion_matrix ( y_true, y_pred ) )

print ( classification_report ( y_true, y_pred ) )


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
Test accuracy: 0.963
Confusion matrix: 
[[ 972    1    2    0    0    2    1    1    1    0]
 [   0 1096    8    5    1    0    5    9   11    0]
 [   8    0 1010    0    3    0    3    4    4    0]
 [   3    1   25  956    0    6    0    4    8    7]
 [   1    0    0    1  944    0   24    0    0   12]
 [   6    0    2   11    1  854   10    1    2    5]
 [  16    2    0    0    3    4  931    0    2    0]
 [   3    3   31    3    4    0    0  973    2    9]
 [   5    0   12    6    6    8    5    2  926    4]
 [   8    4    1    4    9    3    1    6    5  968]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       980
           1       0.99      0.97      0.98      1135
           2       0.93      0.98      0.95      1032
           3       0.97      0.95      0.96      1010
           4       0.97      0.96      0.97       982
           5       0.97      0.96      0.97       892
         